smtp:
  user_name: 'youremail@gmail.com'
  password: 'xxxx xxxx xxxx xxxx'
cloudinary:
  url: 'cloudinary://111111111111111:xxxxxxxxxxxxxxxxxxxxxxxxxxx@x1x1x1x1x'
  key: '111111111111111'
  secret: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx'
  name: 'x1x1x1x1x'
  folder: 'yourfolder'